### ISSUE TITLE
Update user's attribute in create-auth-challenge instead of login lambda

### ISSUE THREAD

**Issue by timoha** [leanmotherfuckers/serverless-magic-links-poc#19]
Thank you for this PoC, I'm trying to emulate similar flow however was wondering about your choice to update user attribute in a custom `login` lambda instead of in `create-auth-challenge`. I'm probably missing some problem and wondering if you could explain the rationale.

**Comment by tschoffelen** [comment]
That's what we were doing originally as well, but there are two UX problems with that approach that didn't work for our use case:

* Cognito auth challenges are limited to a very short timeout, and we found that some users needed more time to click the link in the email.
* Auth challenges require some state to be saved on the client, meaning that you need to open the link from the email in the same browser/session from which you initiated the login. That causes problems if people use multiple browsers (very common on Windows, where the user might initiate the login from Chrome, but clicking the email link opens Edge) or try to open the link on a different device. There are also other reasons localStorage or cookies might not persist, even if using the same browser, which could make the login fail.

That's why this felt like the best solution given the limitations, but it's indeed not the cleanest. We've been using this in production for 1+ yr now, and it's surprisingly stable though.

**Comment by timoha** [comment]
I see, thank you @tschoffelen! These are great points and these are the issues I'll definitely need to handle as well in our product.
